services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

  localstack:
    image: localstack/localstack:latest
    hostname: localstack
    ports:
      - "4566:4566"
      - 4510-4559:4510-4559
    environment:
      SERVICES: sqs,s3
      DEBUG: 1
      DATA_DIR: ${DATA_DIR-}
      DOCKER_HOST: unix:///var/run/docker.sock
      LOCALSTACK_HOST: localstack
    volumes:
      - ${TMPDIR:-/tmp}/localstack:/var/log/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    # restart: on-failure

volumes:
  dynamodb-data:
